# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AddCoordinates
                                 A QGIS plugin
 This plugin takes coordinates, plots on the map and saves them.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-02-11
        copyright            : (C) 2026 by Wongani Msukwa
        email                : GISDevs
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load AddCoordinates class from file AddCoordinates.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .add_coordinates import AddCoordinates
    return AddCoordinates(iface)
